config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("", include("movies.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MoviesView.as_view(), name='index'), # Главная страница
    path("detail/<int:pk>/", views.MovieDetailView.as_view(), name='movie_detail'),  # Детальная страница с Фильмами
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),  # Детальная страница Актера
    path("films/", views.FilmsView.as_view(), name='films'), # Страница с Фильмами
    path("anime/", views.AnimeView.as_view(), name='anime'), # Страница с Аниме
    path("serials/", views.SerialsView.as_view(), name='serials'), # Страница с Сериалами
    path("detail/comment/create/<int:post_id>/", views.CommentCreateView.as_view(), name="create_comment"), # Комментарии/Отзывы
    path("catalog/list/", views.CatalogListView.as_view(), name='catalog'), # Страница со всеми категориями
    path('catalog/list/new/', views.catalog_list, name='catalog_list'),  # Страница поиска всех категорий
    path('serials/list/new/', views.serials_list, name='serials_list'), # Страница поиска Сериалов
    path('films/list/new/', views.films_list, name='films_list'), # Страница поиска Фильмов
    path('anime/list/new/', views.anime_list, name='anime_list'), # Страница поиска Аниме
    path("search/", views.Search.as_view(), name='search'), # Страница поиска
    path('about/', views.about, name='about'),  # О сайте




]

movies/models.py
# Create your models here.
from django.db import models
from accounts.models import User
from datetime import date
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Фильм"""
    title = models.CharField("Название", max_length=255)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveBigIntegerField("Дата выхода", default=2022)
    country = models.CharField("Страна", max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name="Режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="Актёры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveBigIntegerField("Бюджет", default=0, help_text="Указывать сумму в долларах")
    fees_in_usa = models.PositiveBigIntegerField("Сборы в США", default=0, help_text="Указывать сумму в долларах")
    fees_in_world = models.PositiveBigIntegerField("Сборы в мире", default=0, help_text="Указывать сумму в долларах")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)
    video = models.FileField(upload_to="movies/videos", blank=True, null=True)
    age_category = models.PositiveBigIntegerField("Возрастная категория", default=16)
    trailer_url = models.URLField("Ссылка на трейлер", blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=150)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class Comment(models.Model):
    """Комментарии/Отзывы"""
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Автор")
    post = models.ForeignKey(Movie, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Пост", related_name="comments")
    text = models.TextField("Комментарий")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.text

movies/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text",]
        widgets = {
            "text": forms.Textarea(attrs={"class": "form__textarea", "placeholder":"Добавить отзыв"})
        }

movies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.base import View

from .forms import CommentCreateForm
from .models import Movie, Actor, Genre, Comment

from django.db.models import Q


class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class MoviesView(GenreYear, ListView):
    """Список всех категорий на главной странице"""
    model = Movie
    # queryset = Movie.objects.filter(draft=False)
    queryset = Movie.objects.filter(draft=False).order_by('-id')

    paginate_by = 8
    template_name = "movies/movie_list.html"


class FilmsView(GenreYear, ListView):
    """Список всех фильмов"""
    model = Movie
    # queryset = Movie.objects.filter(draft=False)
    queryset = Movie.objects.filter(category="1", draft=False).order_by('-id')
    paginate_by = 4
    template_name = "movies/films.html"


class AnimeView(GenreYear, ListView):
    """Список всех аниме"""
    model = Movie
    queryset = Movie.objects.filter(category="2", draft=False).order_by('-id')
    paginate_by = 4
    template_name = "movies/anime.html"


class SerialsView(GenreYear, ListView):
    """Список всех сериалов"""
    model = Movie
    queryset = Movie.objects.filter(category="3", draft=False).order_by('-id')

    paginate_by = 4
    template_name = "movies/serials.html"


class CatalogListView(ListView):
    """Список всех категорий на страничке ВСЕ КАТЕГОРИИ"""
    template_name = "movies/catalog.html"
    model = Movie
    paginate_by = 4
    queryset = Movie.objects.filter(draft=False).order_by('-id')
    # queryset = Movie.objects.filter(draft=False)


class MovieDetailView(GenreYear, DetailView):
    """Детальная страница фильма с описанием"""
    template_name = "movies/movie_detail.html"
    model = Movie
    # slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentCreateForm()
        return context


class ActorView(Genre, DetailView):
    """Вывод информации о актере"""
    model = Actor
    movie = Movie.objects.filter(draft=False).order_by('-id')
    template_name = "movies/actor.html"
    slug_field = "name"
    queryset = Actor.objects.order_by('-id')


class FilterMoviesView(GenreYear, ListView):
    """Фильтрация всех категорий"""
    # template_name = "movies/catalog.html"
    # paginate_by = 1

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class Search(ListView):
    """Поиск фильмов"""
    # template_name = 'index.html'
    # context_object_name = 'films'
    # paginate_by = 1

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q")).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context


class CommentCreateView(LoginRequiredMixin, FormView):
    """Комментарии/Отзывы"""
    form_class = CommentCreateForm
    model = Comment

    def form_valid(self, form):
        post_id = self.kwargs.get("post_id")
        post = get_object_or_404(Movie, id=post_id)
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = post
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("movie_detail", kwargs={"pk":self.kwargs.get("post_id")})


def catalog_list(request):
    """Страница поиска всех категорий"""
    genre = request.GET.get('genre')
    year = request.GET.get('year')

    # Инициализация queryset'а
    movies = Movie.objects.all()

    # Фильтрация по жанру
    if genre:
        movies = movies.filter(genres__name=genre).order_by('-id')

    # Фильтрация по году
    if year:
        movies = movies.filter(year=year).order_by('-id')

    context = {
        'movies': movies
    }

    return render(request, 'movies/catalog.html', context)


def anime_list(request):
    """Страница поиска всех аниме"""
    genre = request.GET.get('genre')
    year = request.GET.get('year')

    # Инициализация queryset'а
    movies = Movie.objects.all()

    # Фильтрация по жанру
    if genre:
        movies = movies.filter(genres__name=genre, category="2").order_by('-id')

    # Фильтрация по году
    if year:
        movies = movies.filter(year=year, category="2").order_by('-id')

    context = {
        'movies': movies
    }

    return render(request, 'movies/anime.html', context)


def films_list(request):
    """Страница поиска всех фильмов"""
    genre = request.GET.get('genre')
    year = request.GET.get('year')

    # Инициализация queryset'а
    movies = Movie.objects.all()

    # Фильтрация по жанру
    if genre:
        movies = movies.filter(genres__name=genre, category="1").order_by('-id')

    # Фильтрация по году
    if year:
        movies = movies.filter(year=year, category="1").order_by('-id')

    context = {
        'movies': movies
    }

    return render(request, 'movies/films.html', context)


def serials_list(request):
    """Страница поиска всех скриалов"""
    genre = request.GET.get('genre')
    year = request.GET.get('year')

    # Инициализация queryset'а
    movies = Movie.objects.all()

    # Фильтрация по жанру
    if genre:
        movies = movies.filter(genres__name=genre, category="3").order_by('-id')

    # Фильтрация по году
    if year:
        movies = movies.filter(year=year, category="3").order_by('-id')

    context = {
        'movies': movies
    }

    return render(request, 'movies/serials.html', context)


def about(request):
    """Страница О сайте"""
    return render(request, 'movies/about.html')


def movie_trailer(request, pk):
    """Вывод трейлера"""
    movie = get_object_or_404(Movie, pk=pk)
    context = {'movie': movie}
    return render(request, 'movies/movie_detail.html', context)












# @login_required
# def index(request):
#     # tasks = Task.objects.find() - Найти по id
#     # tasks = Task.objects.order - Произвести сортировку
#     # tasks = Task.objects.order_by('-id')[:1] - Сортировка по id в обратном порядке, лишь по одной записи
#     tasks = Category.Movie.title.objects.order_by('-id')[:1]
#     return render(request, 'movies/movie_detail.html', {'title': 'Главная страница сайта', 'tasks': tasks})

movies/templates/movies/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
	<!-- page title -->
	<section class="section section--first section--bg" data-bg="{% static 'img/section/section' %}.jpg">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<!-- section title -->
						<h2 class="section__title">О сайте</h2>
						<!-- end section title -->

						<!-- breadcrumb -->
						<ul class="breadcrumb">
							<li class="breadcrumb__item"><a href="{% url 'index' %}">Главная</a></li>
							<li class="breadcrumb__item breadcrumb__item--active">О сайте</li>
						</ul>
						<!-- end breadcrumb -->
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end page title -->

	<!-- pricing -->
	<div class="section">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-6 col-lg-4">
					<div class="price price--premium">
						<div class="price__item price__item--first"><span>Визуальная часть сайта</span><span>☑</span></div>
						<div class="price__item" style="color:white;"><span>Кнопки и их расположение</span>☑</div>
						<div class="price__item" style="color:white;"><span>Логотип</span>☑</div>
						<div class="price__item" style="color:white;"><span>Размер изображений</span>☑</div>
						<div class="price__item" style="color:white;"><span>Фон</span>☑</div>
						<div class="price__item" style="color:white;"><span>Цвет шрифта</span>☑</div>
						<a href="{% url 'index' %}" class="price__btn">Перейти на главную</a>
					</div>
				</div>

				<div class="col-12 col-md-6 col-lg-4">
					<div class="price price--premium">
						<div class="price__item price__item--first"><span>Функциональная часть сайта</span><span>☑</span></div>
						<div class="price__item" style="color:white;"><span>Видеоплеер</span>☑</div>
						<div class="price__item" style="color:white;"><span>Вывод последних добавленных фильмов и актёров</span>☑</div>
						<div class="price__item" style="color:white;"><span>Детальная страница с актёрами</span>☑</div>
						<div class="price__item" style="color:white;"><span>Детальная страница с фильмами</span>☑</div>
						<div class="price__item" style="color:white;"><span>Изменения в административной панели</span>☑</div>
						<div class="price__item" style="color:white;"><span>Кадры к фильмам</span>☑</div>
						<div class="price__item" style="color:white;"><span>Логин и Регистрация</span>☑</div>
						<div class="price__item" style="color:white;"><span>Отзывы/Комментарии к фильмам</span>☑</div>
						<div class="price__item" style="color:white;"><span>Пагинация</span>☑</div>
						<div class="price__item" style="color:white;"><span>Перенос базы с SQLite Version 3 на PostgreSQL</span>☑</div>
						<div class="price__item" style="color:white;"><span>Поиск</span>☑</div>
						<div class="price__item" style="color:white;"><span>Полная информация и описание к фильмам/актёрам</span>☑</div>
						<div class="price__item" style="color:white;"><span>Разделение по категориям</span>☑</div>
						<div class="price__item" style="color:white;"><span>Трейлер, возраст.категория и прочее</span>☑</div>
						<div class="price__item" style="color:white;"><span>Фильтрация по жанрам и годам</span>☑</div>
						<a href="{% url 'index' %}" class="price__btn">Перейти на главную</a>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="price price--premium">
						<div class="price__item price__item--first"><span>Используемое ПО и Дополнения</span><span>☑</span></div>
						<div class="price__item" style="color:white;"><span>PyCharm v2022.3.2 (Community Edition)</span>☑</div>
						<div class="price__item" style="color:white;"><span>Mozilla Firefox v110.0</span>☑</div>
						<div class="price__item" style="color:white;"><span>dbdiagram.io</span>☑</div>
						<div class="price__item" style="color:white;"><span>Библиотека Django v4.1.6</span>☑</div>
						<div class="price__item" style="color:white;"><span>Библиотека Pillow v9.4.0</span>☑</div>
						<div class="price__item" style="color:white;"><span>Django CKEditor v6.5.1</span>☑</div>
						<div class="price__item" style="color:white;"><span>Подключил статические файлы</span>☑</div>
						<div class="price__item" style="color:white;"><span>Использовал CSRF-token</span>☑</div>
						<a href="{% url 'index' %}" class="price__btn">Перейти на главную</a>
					</div>
				</div>

			</div>
		</div>
	</div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}
{% block javascript %}
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

	<section class="section details">
		<!-- details background -->
		<div class="details__bg" data-bg="{% static 'img/home/1.jpg' %}"></div>
		<!-- end details background -->
		<div class="container">
			<div class="row">
				<!-- title -->
				<div class="col-12">
					<h1 class="details__title">{{ movie.title }}</h1>
				</div>
				<!-- end title -->
				<!-- content -->
				<div class="col-10">
					<div class="card card--details card--series">
						<div class="row">
							<!-- card cover -->
							<div class="col-12 col-sm-4 col-md-4 col-lg-3 col-xl-3">
								<div class="card__cover">
									<img src="{{ movie.poster.url }}" alt="">
								</div>
							</div>
							<!-- end card cover -->
							<!-- card content -->
							<div class="col-12 col-sm-8 col-md-8 col-lg-9 col-xl-9">
								<div class="card__content">
									<div class="card__wrap">
										<ul class="card__list" style="margin-left: -0em;">
													<li>{{ movie.age_category }}+</li>
													<li>{{ movie.year }}</li>
													<li><a href="{{ movie.trailer_url }}">ПОСМОТРЕТЬ ТРЕЙЛЕР</a></li>
										</ul>
									</div>

									<ul class="card__meta">
										    <li><span><b style="color:#32CD32;">Актёры:</b></span>
											{% for actor in movie.actors.all %}
											<a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a>{% endfor %}</li>

										    <li><span><b style="color:#32CD32;">Режиссёры:</b></span>
											{% for director in movie.directors.all %}
											<a href="{{ director.get_absolute_url }}">{{ director.name }}</a>{% endfor %}</li>

										<li><span><b style="color:#32CD32;"> Жанр:</b></span>
											<b href="#" style="color:white;">
												{% for genre in movie.genres.all %}
												{{ genre.name }}
												{% endfor %}</b>
										</li>
										<li><span><b style="color:#32CD32;">Дата выхода:</b></span><b style="color:white;">{{ movie.year }}</b></li>
										<li><span><b style="color:#32CD32;">Возрастная категория:</b></span><b style="color:white;">{{ movie.age_category }}</b></li>
										<li><span><b style="color:#32CD32;">Страна:</b></span> <b href="#" style="color:white;">{{ movie.country }}</b> </li>
										<li><span><b style="color:#32CD32;">Премьера в мире:</b></span> <b href="#" style="color:white;">{{ movie.world_premiere }}</b> </li>
										<li><span><b style="color:#32CD32;">Бюджет:</b></span> <b href="#" style="color:white;">{{ movie.budget }} $</b> </li>
										<li><span><b style="color:#32CD32;">Сборы в мире:</b></span> <b href="#" style="color:white;">{{ movie.fees_in_world }} $</b> </li>
										<li><span><b style="color:#32CD32;">Сборы в США:</b></span> <b href="#" style="color:white;">{{ movie.fees_in_usa }} $</b> </li>
										<li><span><b style="color:#32CD32;">Страна:</b></span> <b href="#" style="color:white;">{{ movie.country }}</b> </li>


									<div class="card__meta">
									 <span><b style="color:#32CD32;">Слоган:</b></span><b style="color:white;">{{ movie.tagline }}</b>
									</div>


									<div class="card__meta">
									 <span><b style="color:#32CD32;">Описание:</b></span><b style="color:white;">{{ movie.description|safe }}</b>
										{% csrf_token %}
									</div>
										</ul>
								</div>
							</div>
							<!-- end card content -->
						</div>
					</div>
				</div>
				<!-- end content -->
				<!-- player -->
				<div class="col-12 col-xl-12">
					<video controls crossorigin playsinline poster="#" id="player">
						<!-- Video files -->
						<source src="{{ movie.video.url }}" type="video/mp4" size="720">

						<!-- Caption files -->
						<track kind="captions" label="English" srclang="en" src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.en.vtt"
						    default>
						<track kind="captions" label="Français" srclang="fr" src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.fr.vtt">
						<a href="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" download>Download</a>
					</video>
				</div>
				<!-- end player -->
				<div class="col-12">
					<div class="details__wrap">
						<!-- availables -->
						<div class="details__devices">
							<span class="details__devices-title">Доступно на устройствах:</span>
							<ul class="details__devices-list">
								<li><i class="icon ion-logo-apple"></i><span>IOS</span></li>
								<li><i class="icon ion-logo-android"></i><span>Android</span></li>
								<li><i class="icon ion-logo-windows"></i><span>Windows</span></li>
								<li><i class="icon ion-md-tv"></i><span>Smart TV</span></li>
							</ul>
						</div>
						<!-- end availables -->

						<!-- share -->
						<div class="details__share">
							<span class="details__share-title">Поделиться:</span>

							<ul class="details__share-list">
								<li class="facebook"><a href="https://m.facebook.com/login/?locale2=ru_RU"><i class="icon ion-logo-facebook"></i></a></li>
								<li class="instagram"><a href="https://www.instagram.com/"><i class="icon ion-logo-instagram"></i></a></li>
								<li class="twitter"><a href="https://twitter.com/login?lang=ru"><i class="icon ion-logo-twitter"></i></a></li>
								<li class="vk"><a href="https://vk.com/feed"><i class="icon ion-logo-vk"></i></a></li>
							</ul>
						</div>
						<!-- end share -->
					</div>
				</div>
			</div>
		</div>
		<!-- end details content -->
	</section>
	<!-- end details -->

	<!-- content -->
	<section class="content">
		<div class="content__head">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<!-- content title -->
						<h2 class="paginator" style="color:white; margin-left: 0em;">Узнать больше</h2>
						<!-- end content title -->
						<!-- content tabs nav -->
						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link active" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Отзывы</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Кадры из фильма</a>
							</li>
						</ul>
						<!-- end content tabs nav -->
						<!-- content mobile tabs nav -->
						<div class="content__mobile-tabs" id="content__mobile-tabs">
							<div class="content__mobile-tabs-btn dropdown-toggle" role="navigation" id="mobile-tabs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<input type="button" value="Comments">
								<span></span>
							</div>

							<div class="content__mobile-tabs-menu dropdown-menu" aria-labelledby="mobile-tabs">
								<ul class="nav nav-tabs" role="tablist">
									<li class="nav-item"><a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Комментарий</a></li>
									<li class="nav-item"><a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Кадры из фильма</a></li>
								</ul>
							</div>
						</div>
						<!-- end content mobile tabs nav -->
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8 col-xl-8">
					<!-- content tabs -->
					<div class="tab-content" id="myTabContent">
						<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
							<div class="row">
								<!-- comments -->
								<div class="col-12">
									<div class="comments">
										<ul class="comments__list">
											  {% for comment in object.comments.all%}
											<li class="comments__item">
												<div class="comments__autor">
													<img class="comments__avatar" src="{% static 'img/user.jpg' %}" alt="">
													<span class="comments__name">{{comment.author.email}}</span>
													<span class="comments__time">{{comment.created}}</span>
												</div>
												<p class="comments__text">{{comment.text}}</p>
											</li>
											{% endfor %}
										</ul>
										<form action="{% url 'create_comment' movie.id %}" class="form" method="post">
										{% csrf_token %}
										{{ comment_form }}
										<button class="btn btn-info" type="submit"><a class="form__btn" style="color:white;">Отправить</a></button>
										</form>
									</div>
								</div>
								<!-- end comments -->
							</div>
						</div>

						<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab">
							<!-- project gallery -->
							<div class="gallery" itemscope>
								<div class="row">
									<!-- gallery item -->
									{% for image in movie.movieshots_set.all %}
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="{{ image.image.url }}" itemprop="contentUrl" data-size="720x1080">
											<img src="{{ image.image.url }}" itemprop="thumbnail" alt="{{ image.image.url }}" />
										</a>
										<figcaption itemprop="caption description">{{ image.title }}</figcaption>
									</figure>
									{% endfor %}
									<!-- end gallery item -->
								</div>
							</div>
							<!-- end project gallery -->
						</div>
					</div>
					<!-- end content tabs -->
				</div>

					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block javascript %}

{% endblock %}
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
	<script src="{% static 'js/jquery.mCustomScrollbar.min.js' %}"></script>
	<script src="{% static 'js/wNumb.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/plyr.min.js' %}"></script>
	<script src="{% static 'js/jquery.morelines.min.js' %}"></script>
	<script src="{% static 'js/photoswipe.min.js' %}"></script>
	<script src="{% static 'js/photoswipe-ui-default.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>